# Generated by Django 5.2 on 2025-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_academicexperience_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
