# Generated by Django 5.2 on 2025-06-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_career_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicexperience',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
