# Generated by Django 5.2 on 2025-07-12 20:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_academicexperience_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
