# Generated by Django 5.2 on 2025-07-12 20:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_alter_career_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicexperience',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='formaciones/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='projects/'),
        ),
    ]
